
language: r
latex: false
fortran: false
pandoc: false

warnings_are_errors: true
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - libapparmor-dev
  
install: Rscript ./install_deps.R
  
script: Rscript ./run_test_suites.R
