
language: r
latex: false
fortran: false
pandoc: false

warnings_are_errors: true
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - libapparmor-dev

r_github_packages:
  - antonellilab/outsider.base
  - antonellilab/outsider
  - antonellilab/outsider.devtools
  
install: skip
  
script: Rscript ./run_test_suites.R
