
language: r
latex: false
fortran: false
pandoc: false

warnings_are_errors: true
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - libapparmor-dev
  
install:
  - R -e "remotes::install_github(repo = 'antonellilab/outsider.base')"
  - R -e "remotes::install_github(repo = 'antonellilab/outsider')"
  - R -e "remotes::install_github(repo = 'antonellilab/outsider.devtools')"
  
script:
  - pwd
  - Rscript -e run_test_suites.R
